config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'app#home'

  get '/app', to: 'app#app'
  get '/changelog', to: 'app#changelog'

  namespace :api do
    resources :activities, except: [:index]
    resources :elements, except: [:index] do
      resources :activities, only: [:index]
    end
    resources :resource_interactions
    resources :layers
    resources :maps do
      get :picture, on: :member
      resources :activities, only: [:index]
      resources :patches, only: [:index]
      resources :elements, only: [:index]
    end
    resources :patches, except: [:index] do
      resources :elements, only: [:index]
    end
    resources :genera
    resources :resources do
      resources :resource_interactions, only: [:index], path: 'interactions'
    end
  end

  namespace :admin do
    resources :layers
    resources :genera
    resources :resource_interactions
    resources :resources
  end
end

app/controllers/admin/resource_interactions_controller.rb
module Admin
  class ResourceInteractionsController < AdminApplicationController
    before_action :set_resource_interaction, only: [:show, :edit, :update, :destroy]

    # GET /admin/resource_interactions
    def index
      @resource_interactions = policy_scope ResourceInteraction.all
    end

    # GET /admin/resource_interactions/1
    def show; end

    # GET /admin/resource_interactions/new
    def new
      authorize ResourceInteraction

      @resource_interaction = ResourceInteraction.new
    end

    # GET /admin/resource_interactions/1/edit
    def edit; end

    # POST /admin/resource_interactions
    def create
      authorize ResourceInteraction

      @resource_interaction = ResourceInteraction.new(resource_interaction_params)

      if @resource_interaction.save
        redirect_to admin_resource_interaction_path(@resource_interaction), notice: I18n.t('admin.resource_interactions.create.success')
      else
        render :new
      end
    end

    # PATCH/PUT /admin/resource_interactions/1
    def update
      if @resource_interaction.update(resource_interaction_params)
        redirect_to admin_resource_interaction_path(@resource_interaction), notice: I18n.t('admin.resource_interactions.update.success')
      else
        render :edit
      end
    end

    # DELETE /admin/resource_interactions/1
    def destroy
      @resource_interaction.destroy
      redirect_to admin_resource_interactions_url, notice: I18n.t('admin.resource_interactions.destroy.success')
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_resource_interaction
      @resource_interaction = ResourceInteraction.find(params[:id])

      authorize @resource_interaction
    end

    # Only allow a trusted parameter "white list" through.
    def resource_interaction_params
      parameters = params.require(:resource_interaction).permit(:nature, :notes, :subject_id, :target_id)
      parameters[:nature] = parameters[:nature].to_i if parameters[:nature].present?
      parameters
    end
  end
end

app/controllers/api/resource_interactions_controller.rb
module Api
  class ResourceInteractionsController < ApiApplicationController
    before_action :set_resource_interaction, only: [:show, :update, :destroy]

    # GET /resource_interactions
    def index
      @resource_interactions = policy_scope ResourceInteraction
      @resource_interactions = @resource_interactions.with_resource(params[:resource_id]) if params[:resource_id]

      render 'api/resource_interactions/index'
    end

    # GET /resource_interactions/1
    def show
      render 'api/resource_interactions/show'
    end

    # POST /resource_interactions
    def create
      authorize ResourceInteraction
      @resource_interaction = ResourceInteraction.new(resource_interaction_params)

      if @resource_interaction.save
        render 'api/resource_interactions/show', status: :created, location: api_resource_interaction_url(@resource_interaction)
      else
        render json: @resource_interaction.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /resource_interactions/1
    def update
      if @resource_interaction.update(resource_interaction_params)
        render 'api/resource_interactions/show', status: :ok, location: api_resource_interaction_url(@resource_interaction)
      else
        render json: @resource_interaction.errors, status: :unprocessable_entity
      end
    end

    # DELETE /resource_interactions/1
    def destroy
      @resource_interaction.destroy
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_resource_interaction
      @resource_interaction = ResourceInteraction.find(params[:id])

      authorize @resource_interaction
    end

    # Only allow a trusted parameter "white list" through.
    def resource_interaction_params
      params.require(:resource_interaction).permit(:subject_id, :target_id, :nature, :notes)
    end
  end
end

app/views/admin/resource_interactions/_form.html.haml
- url = resource_interaction.id ? admin_resource_interaction_path : admin_resource_interactions_path
= form_for resource_interaction, url: url, html: { class: 'form' } do |f|
  - if resource_interaction.errors.any?
    .alert.alert--alert
      %p= t('.errors', count: resource_interaction.errors.count)
      %ul
        - resource_interaction.errors.full_messages.each do |message|
          %li= message

  .grid.grid--3
    %div
      .field
        = f.label :subject_id, t('activerecord.attributes.resource_interaction.subject')
        = f.collection_select :subject_id, Resource.all.order(:name), :id, :name, prompt: true, required: true
    %div
      .field
        = f.label :nature
        = f.select :nature, ResourceInteraction.natures.keys, prompt: true, html: { required: true }
    %div
      .field
        = f.label :target_id, t('activerecord.attributes.resource_interaction.target')
        = f.collection_select :target_id, Resource.all.order(:name), :id, :name, prompt: true, html: { required: true }
  .field
    = f.label :notes
    = f.text_field :notes

  .form__actions
    = f.submit t('generic.save'), class: 'recorder'

app/views/admin/resource_interactions/edit.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('generic.back'), :admin_resource_interactions, role: 'button'
  = link_to t('generic.show'), @admin_resource_interaction, role: 'button'
  = link_to t('generic.destroy'),
            @admin_resource_interaction,
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button'

= render 'form', resource_interaction: @resource_interaction

app/views/admin/resource_interactions/index.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('.new'), new_admin_resource_interaction_path, role: 'button', class: 'creative'

- if @resource_interactions.count.zero?
  .alert.alert--empty= t('.no_content')
- else
  %table
    %thead
      %tr
        %th= t('activerecord.attributes.resource_interaction.subject')
        %th= t('activerecord.attributes.resource_interaction.nature')
        %th= t('activerecord.attributes.resource_interaction.target')
        %th= t('activerecord.attributes.resource_interaction.notes')
        %th

    %tbody
      - @resource_interactions.each do |resource_interaction|
        %tr
          %td= resource_interaction.subject.name
          %td
            &rarr;
            = link_to resource_interaction.nature, admin_resource_interaction_path(resource_interaction)
            &rarr;
          %td= resource_interaction.target.name
          %td= resource_interaction.notes
          %td.actions
            = link_to t('generic.edit'), edit_admin_resource_interaction_path(resource_interaction), role: 'button'
            = link_to t('generic.destroy'),
                      admin_resource_interaction_path(resource_interaction),
                      method: :delete,
                      data: { confirm: t('generic.are_you_sure') },
                      role: 'button',
                      class: 'destructive'

app/views/admin/resource_interactions/new.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('generic.back'), admin_resource_interactions_path, role: 'button'

= render 'form', resource_interaction: @resource_interaction

app/views/admin/resource_interactions/show.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('generic.back'), admin_resource_interactions_path, role: 'button'

  - if policy([:admin, @resource_interaction]).edit?
    = link_to t('generic.edit'), edit_admin_resource_interaction_path(@resource_interaction), role: 'button'
  - if policy([:admin, @resource_interaction]).destroy?
    = link_to t('generic.destroy'),
              admin_resource_interaction_path,
              method: :delete,
              data: { confirm: t('generic.are_you_sure') },
              role: 'button',
              class: 'destructive'
.page--show
  %aside.page__panel
    %section
      %dl
        %dt= t('generic.definition', value: t('activerecord.attributes.resource_interaction.subject'))
        %dd= @resource_interaction.subject.name

        %dt= t('generic.definition', value: t('activerecord.attributes.resource_interaction.nature'))
        %dd= @resource_interaction.nature

        %dt= t('generic.definition', value: t('activerecord.attributes.resource_interaction.target'))
        %dd= @resource_interaction.target.name

  .page__content
    %h2= t('activerecord.attributes.resource_interaction.notes')
    = @resource_interaction.notes