config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'app#home'

  get '/app', to: 'app#app'
  get '/changelog', to: 'app#changelog'

  namespace :api do
    resources :activities, except: [:index]
    resources :elements, except: [:index] do
      resources :activities, only: [:index]
    end
    resources :resource_interactions
    resources :layers
    resources :maps do
      get :picture, on: :member
      resources :activities, only: [:index]
      resources :patches, only: [:index]
      resources :elements, only: [:index]
    end
    resources :patches, except: [:index] do
      resources :elements, only: [:index]
    end
    resources :genera
    resources :resources do
      resources :resource_interactions, only: [:index], path: 'interactions'
    end
  end

  namespace :admin do
    resources :layers
    resources :genera
    resources :resource_interactions
    resources :resources
  end
end

app/models/layer.rb
class Layer < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  # FIXME: Create custom validator
  validates :color, presence: true

  has_many :resources, dependent: :restrict_with_exception
end

app/controllers/admin/layers_controller.rb
module Admin
  class LayersController < AdminApplicationController
    before_action :set_layer, only: [:show, :edit, :update, :destroy]

    # GET /admin/layers
    def index
      @layers = policy_scope(Layer)
    end

    # GET /admin/layers/1
    def show; end

    # GET /admin/layers/new
    def new
      authorize Layer

      @layer = Layer.new
    end

    # GET /admin/layers/1/edit
    def edit; end

    # POST /admin/layers
    def create
      authorize Layer

      @layer = Layer.new(layer_params)

      if @layer.save
        redirect_to admin_layer_path(@layer), notice: I18n.t('admin.layers.create.success')
      else
        render :new
      end
    end

    # PATCH/PUT /admin/layers/1
    def update
      if @layer.update(layer_params)
        redirect_to admin_layer_path(@layer), notice: I18n.t('admin.layers.update.success')
      else
        render :edit
      end
    end

    # DELETE /admin/layers/1
    def destroy
      @layer.destroy
      redirect_to admin_layers_url, notice: I18n.t('admin.layers.destroy.success')
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_layer
      @layer = Layer.find(params[:id])

      authorize @layer
    end

    # Only allow a trusted parameter "white list" through.
    def layer_params
      params.require(:layer).permit(:name, :color, :description)
    end
  end
end

app/controllers/api/layers_controller.rb
module Api
  class LayersController < ApiApplicationController
    before_action :set_layer, only: [:show, :update, :destroy]

    # GET /layers
    def index
      @layers = policy_scope Layer

      render 'api/layers/index'
    end

    # GET /layers/1
    def show
      render 'api/layers/show'
    end

    # POST /layers
    def create
      authorize Layer
      @layer = Layer.new(layer_params)

      if @layer.save
        render 'api/layers/show', status: :created, location: api_layer_url(@layer)
      else
        render json: @layer.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /layers/1
    def update
      if @layer.update(layer_params)
        render 'api/layers/show', location: api_layer_url(@layer)
      else
        render json: @layer.errors, status: :unprocessable_entity
      end
    end

    # DELETE /layers/1
    def destroy
      @layer.destroy
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_layer
      @layer = Layer.find(params[:id])

      authorize @layer
    end

    # Only allow a trusted parameter "white list" through.
    def layer_params
      params.require(:layer).permit(:name, :description, :color)
    end
  end
end

app/views/admin/layers/_form.html.haml
- url = layer.id ? admin_layer_path : admin_layers_path
= form_for layer, url: url, html: { class: 'form' } do |f|
  - if layer.errors.any?
    .alert.alert--alert
      %p= t('.errors', count: layer.errors.count)
      %ul
        - layer.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :color
    = f.text_field :color
  .field
    = f.label :description
    = f.text_area :description, class: 'textarea-markdown'

  .form__actions
    = f.submit t('generic.save'), class: 'recorder'

app/views/admin/layers/edit.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('generic.back'), :admin_layers, role: 'button'
  = link_to t('generic.show'), @admin_layer, role: 'button'
  = link_to t('generic.destroy'),
            @admin_layer,
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button'

= render 'form', layer: @layer

app/views/admin/layers/index.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('.new'), new_admin_layer_path, role: 'button', class: 'creative'

- if @layers.count.zero?
  .alert.alert--empty= t('.no_content')
- else
  %table
    %thead
      %tr
        %th= t('activerecord.attributes.layer.name')
        %th= t('activerecord.attributes.layer.color')
        %th= t('activerecord.attributes.layer.description')
        %th

    %tbody
      - @layers.each do |layer|
        %tr
          %td= link_to layer.name, admin_layer_path(layer)
          %td= layer.color
          %td= layer.description
          %td.actions
            = link_to t('generic.edit'), edit_admin_layer_path(layer), role: 'button'
            = link_to t('generic.destroy'),
                      admin_layer_path(layer),
                      method: :delete,
                      data: { confirm: t('generic.are_you_sure') },
                      role: 'button',
                      class: 'destructive'

app/views/admin/layers/new.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('generic.back'), admin_layers_path, role: 'button'

= render 'form', layer: @layer

app/views/admin/layers/show.html.haml
- @page_title = t('.title', name: @layer.name)

.page__actions
  = link_to t('generic.back'), admin_layers_path, role: 'button'

  - if policy([:admin, @layer]).edit?
    = link_to t('generic.edit'), edit_admin_layer_path(@layer), role: 'button'
  - if policy([:admin, @layer]).destroy?
    = link_to t('generic.destroy'),
              admin_layer_path,
              method: :delete,
              data: { confirm: t('generic.are_you_sure') },
              role: 'button',
              class: 'destructive'
.page--show
  %aside.page__panel
    %section
      %dl
        %dt= t('generic.definition', value: t('activerecord.attributes.layer.name'))
        %dd= @layer.name

        %dt= t('generic.definition', value: t('activerecord.attributes.layer.color'))
        %dd= @layer.color

  .page__content
    %h2= t('activerecord.attributes.layer.description')
    #markdown
      #markdown-source= @layer.description

:javascript
  renderMD(document.getElementById('markdown'), document.getElementById('markdown-source'))