config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'app#home'

  get '/app', to: 'app#app'
  get '/changelog', to: 'app#changelog'

  namespace :api do
    resources :activities, except: [:index]
    resources :elements, except: [:index] do
      resources :activities, only: [:index]
    end
    resources :resource_interactions
    resources :layers
    resources :maps do
      get :picture, on: :member
      resources :activities, only: [:index]
      resources :patches, only: [:index]
      resources :elements, only: [:index]
    end
    resources :patches, except: [:index] do
      resources :elements, only: [:index]
    end
    resources :genera
    resources :resources do
      resources :resource_interactions, only: [:index], path: 'interactions'
    end
  end

  namespace :admin do
    resources :layers
    resources :genera
    resources :resource_interactions
    resources :resources
  end
end

app/views/admin/resources/_form.html.haml
- url = resource.id ? admin_resource_path : admin_resources_path
= form_for resource, url: url, html: { class: 'form' } do |f|
  - if resource.errors.any?
    .alert.alert--alert
      %p= t('.errors', count: resource.errors.count)
      %ul
        - resource.errors.full_messages.each do |message|
          %li= message

  .page--show
    %section.page__panel
      .field
        = f.label :name
        = f.text_field :name, required: true
      .field
        = f.label :common_names
        = f.text_field :common_names, value: resource.common_names.join(', ')
        .field__help= t('generic.comma_separated_values')
      .field
        = f.label :source
        = f.text_field :source
      .field
        = f.label :edible do
          = f.check_box :edible
          = t('activerecord.attributes.resource.edible')
      .field
        = f.label :parent_id, t('activerecord.attributes.resource.parent')
        = f.collection_select :parent_id, Resource.all.order(:name), :id, :name, prompt: true
      .field
        = f.label :layer_id, t('activerecord.attributes.resource.layer')
        = f.collection_select :layer_id, Layer.all, :id, :name, required: true
      .field
        = f.label :genus_id, t('activerecord.attributes.resource.genus')
        = f.collection_select :genus_id, Genus.all.order(:name), :id, :name, required: true
    %section.page__content
      .field
        = f.label :description
        = f.text_area :description, required: true, class: 'textarea-markdown textarea--large'

  .form__actions
    = f.submit t('generic.save'), class: 'recorder'

app/views/admin/resources/edit.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('generic.back'), :admin_resources, role: 'button'
  = link_to t('generic.show'), @admin_resource, role: 'button'
  = link_to t('generic.destroy'),
            @admin_resource,
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button'

= render 'form', resource: @resource

app/views/admin/resources/index.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('.new'), new_admin_resource_path, role: 'button', class: 'creative'

- if @resources.count.zero?
  .alert.alert--empty= t('.no_content')
- else
  %table
    %thead
      %tr
        %th= t('activerecord.attributes.resource.name')
        %th= t('activerecord.attributes.resource.edible')
        %th= t('activerecord.attributes.resource.parent')
        %th= t('activerecord.attributes.resource.layer')
        %th= t('activerecord.attributes.resource.genus')
        %th

    %tbody
      - @resources.each do |resource|
        %tr
          %td= link_to resource.name, admin_resource_path(resource)
          %td= yes_no resource.edible
          %td= resource.parent.presence&.name || '-'
          %td= resource.layer.name
          %td= resource.genus.name
          %td.actions
            = link_to t('generic.edit'), edit_admin_resource_path(resource), role: 'button'
            = link_to t('generic.destroy'),
                      admin_resource_path(resource),
                      method: :delete,
                      data: { confirm: t('generic.are_you_sure') },
                      role: 'button',
                      class: 'destructive'

app/views/admin/resources/new.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('generic.back'), admin_resources_path, role: 'button'

= render 'form', resource: @resource

app/views/admin/resources/show.html.haml
- @page_title = t('.title', name: @resource.name)

.page__actions
  = link_to t('generic.back'), admin_resources_path, role: 'button'

  - if policy([:admin, @resource]).edit?
    = link_to t('generic.edit'), edit_admin_resource_path(@resource), role: 'button'
  - if policy([:admin, @resource]).destroy?
    = link_to t('generic.destroy'),
              admin_resource_path,
              method: :delete,
              data: { confirm: t('generic.are_you_sure') },
              role: 'button',
              class: 'destructive'
.page--show
  %aside.page__panel
    %section
      %dl
        %dt= t('generic.definition', value: t('activerecord.attributes.resource.layer'))
        %dd= link_to @resource.layer.name, admin_layer_path(@resource.layer)

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.genus'))
        %dd= link_to @resource.genus.name, admin_genus_path(@resource.genus)

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.source'))
        %dd= @resource.source

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.common_names'))
        %dd
          - if @resource.common_names.size.zero?
            \-
          - else
            %ul
              - @resource.common_names.each do |cn|
                %li= cn

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.edible'))
        %dd= yes_no @resource.edible

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.parent'))
        %dd= @resource.parent ? @resource.parent.name : '-'

  .page__content
    %h2= t('activerecord.attributes.resource.description')
    #markdown
      #markdown-source= @resource.description

    - if @resource.parent.blank?
      %h2= t('.resources')
      - if @resource.children.size.zero?
        .alert.alert--mute= t('.no_child_resource')
      - else
        %ul
          - @resource.children.each do |resource|
            %li= link_to resource.name, admin_resource_path(resource)

:javascript
  renderMD(document.getElementById('markdown'), document.getElementById('markdown-source'))