config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'app#home'

  get '/app', to: 'app#app'
  get '/changelog', to: 'app#changelog'

  namespace :api do
    resources :activities, except: [:index]
    resources :elements, except: [:index] do
      resources :activities, only: [:index]
    end
    resources :resource_interactions
    resources :layers
    resources :maps do
      get :picture, on: :member
      resources :activities, only: [:index]
      resources :patches, only: [:index]
      resources :elements, only: [:index]
    end
    resources :patches, except: [:index] do
      resources :elements, only: [:index]
    end
    resources :genera
    resources :resources do
      resources :resource_interactions, only: [:index], path: 'interactions'
    end
  end

  namespace :admin do
    resources :layers
    resources :genera
    resources :resource_interactions
    resources :resources
  end
end

app/views/layouts/_flash_messages.html.haml
- unless flash.empty?
  .flash-messages
    - flash.each do |name, message|
      %div{ class: "alert alert--#{name}" }= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title #{@page_title ? "#{@page_title} - " : ''}Garden Party
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
    = javascript_pack_tag "locales/#{I18n.locale}"
    :javascript
      I18n.locale = '#{I18n.locale}'
  %body
    - if @no_rails_layout
      = yield
    - else
      %nav.main_menu
        .main_menu__links
          = link_to t('.home'), root_path
          - if current_user.present?
            \|
            = link_to t('.app'), app_path
            - if current_user.admin?
              \| Admin:
              = link_to t('.layers'), :admin_layers
              [#{link_to '+', :new_admin_layer}]
              \|
              = link_to t('.genera'), :admin_genera
              [#{link_to '+', :new_admin_genus}]
              \|
              = link_to t('.resources'), :admin_resources
              [#{link_to '+', :new_admin_resource}]
              \|
              = link_to t('.resource_interactions'), :admin_resource_interactions
              [#{link_to '+', :new_admin_resource_interaction}]
          \|
          = link_to t('.changelog'), changelog_path
        - if current_user.present?
          = link_to t('.account'), :edit_user_registration, class: 'button'
          = button_to t('.sign_out'), :destroy_user_session, method: 'delete'
        - else
          = link_to t('.sign_in'), :new_user_session

      .page
        %h1= @page_title

        = render 'layouts/flash_messages'
        = yield